env:
  browser: true
  es2021: true
extends: standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: 2020
  project:
    - backend/tsconfig.json
  sourceType: module
rules:
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/no-extraneous-class": off
  "@typescript-eslint/ban-ts-comment": off
